import {
    Agent,
    Trade,
    Position,
    PoliticalMarket,
    User,
    PerformanceDataPoint,
} from "../types";

// ─── Mock User ───
export const mockUser: User = {
    id: "usr_01HZXK9Q2R3T4V5W6X7Y8Z",
    email: "trader@zuritrade.com",
    walletAddress: "0x7a3B...f42E",
    displayName: "Victor",
    createdAt: "2026-01-15T09:30:00Z",
};

// ─── Mock Markets (African Political) ───
export const mockMarkets: PoliticalMarket[] = [
    {
        id: "mkt_ng_001",
        title: "Will APC win the 2027 Nigerian Presidential Election?",
        description: "Resolves YES if the All Progressives Congress candidate wins the 2027 Nigerian general election as declared by INEC.",
        category: "elections",
        region: "nigeria",
        probability: 0.42,
        volume: 2_450_000,
        totalTraders: 1_847,
        status: "active",
        resolution: null,
        endDate: "2027-02-28T23:59:59Z",
        createdAt: "2026-01-10T00:00:00Z",
    },
    {
        id: "mkt_za_001",
        title: "Will South Africa pass the NHI Bill into full law by Dec 2026?",
        description: "Resolves YES if the National Health Insurance Bill is fully enacted and gazetted by December 31, 2026.",
        category: "policy",
        region: "south-africa",
        probability: 0.35,
        volume: 1_120_000,
        totalTraders: 923,
        status: "active",
        resolution: null,
        endDate: "2026-12-31T23:59:59Z",
        createdAt: "2026-01-05T00:00:00Z",
    },
    {
        id: "mkt_ke_001",
        title: "Will Kenya shilling trade above 150/USD by Q2 2026?",
        description: "Resolves YES if the KES/USD exchange rate exceeds 150 at any point during Q2 2026 per CBK official rates.",
        category: "economics",
        region: "kenya",
        probability: 0.58,
        volume: 890_000,
        totalTraders: 654,
        status: "active",
        resolution: null,
        endDate: "2026-06-30T23:59:59Z",
        createdAt: "2026-01-12T00:00:00Z",
    },
    {
        id: "mkt_gh_001",
        title: "Will Ghana's new president serve full first 100 days without cabinet reshuffle?",
        description: "Resolves YES if no cabinet minister is replaced within the first 100 days of the new administration.",
        category: "policy",
        region: "ghana",
        probability: 0.67,
        volume: 340_000,
        totalTraders: 289,
        status: "active",
        resolution: null,
        endDate: "2026-04-15T23:59:59Z",
        createdAt: "2026-01-08T00:00:00Z",
    },
    {
        id: "mkt_ng_002",
        title: "Will CBN hold interest rates above 20% through Q1 2026?",
        description: "Resolves YES if the Central Bank of Nigeria maintains the Monetary Policy Rate at or above 20% for all of Q1 2026.",
        category: "economics",
        region: "nigeria",
        probability: 0.73,
        volume: 1_560_000,
        totalTraders: 1_102,
        status: "active",
        resolution: null,
        endDate: "2026-03-31T23:59:59Z",
        createdAt: "2026-01-02T00:00:00Z",
    },
    {
        id: "mkt_et_001",
        title: "Will Ethiopia complete the GERD filling by end of 2026?",
        description: "Resolves YES if Ethiopia announces completion of the Grand Ethiopian Renaissance Dam reservoir filling by December 31, 2026.",
        category: "diplomacy",
        region: "ethiopia",
        probability: 0.29,
        volume: 670_000,
        totalTraders: 412,
        status: "active",
        resolution: null,
        endDate: "2026-12-31T23:59:59Z",
        createdAt: "2026-01-20T00:00:00Z",
    },
    {
        id: "mkt_za_002",
        title: "Will ANC retain majority in 2027 Gauteng provincial elections?",
        description: "Resolves YES if the African National Congress wins more than 50% of seats in the 2027 Gauteng provincial legislature elections.",
        category: "elections",
        region: "south-africa",
        probability: 0.18,
        volume: 980_000,
        totalTraders: 756,
        status: "active",
        resolution: null,
        endDate: "2027-05-15T23:59:59Z",
        createdAt: "2026-02-01T00:00:00Z",
    },
    {
        id: "mkt_ke_002",
        title: "Will Kenya's Gen Z protests force a policy reversal on Finance Act 2026?",
        description: "Resolves YES if the Kenyan government withdraws or significantly amends the proposed Finance Act 2026 due to public pressure.",
        category: "policy",
        region: "kenya",
        probability: 0.51,
        volume: 1_230_000,
        totalTraders: 1_415,
        status: "active",
        resolution: null,
        endDate: "2026-09-30T23:59:59Z",
        createdAt: "2026-02-05T00:00:00Z",
    },
];

// ─── Mock Agents ───
export const mockAgents: Agent[] = [
    {
        id: "agt_001",
        userId: mockUser.id,
        name: "Lagos Oracle",
        walletAddress: "0x4B2a...d91F",
        strategyType: "momentum",
        riskLevel: "moderate",
        marketFocus: {
            regions: ["nigeria"],
            categories: ["elections", "economics"],
        },
        maxTradeSize: 500,
        dailyLossLimit: 200,
        positionLimit: 5,
        capitalAllocated: 5000,
        capitalUsed: 3200,
        status: "active",
        pnl: 1247.5,
        pnlPercent: 24.95,
        winRate: 0.72,
        totalTrades: 47,
        openPositions: 3,
        lastTradeAt: "2026-02-12T08:15:00Z",
        deployedAt: "2026-01-18T14:00:00Z",
        createdAt: "2026-01-18T13:45:00Z",
    },
    {
        id: "agt_002",
        userId: mockUser.id,
        name: "Nairobi Hawk",
        walletAddress: "0x9C7e...a23B",
        strategyType: "contrarian",
        riskLevel: "aggressive",
        marketFocus: {
            regions: ["kenya", "ethiopia"],
            categories: ["policy", "economics"],
        },
        maxTradeSize: 1000,
        dailyLossLimit: 500,
        positionLimit: 8,
        capitalAllocated: 10000,
        capitalUsed: 7800,
        status: "active",
        pnl: 3120.0,
        pnlPercent: 31.2,
        winRate: 0.65,
        totalTrades: 83,
        openPositions: 5,
        lastTradeAt: "2026-02-12T09:42:00Z",
        deployedAt: "2026-01-20T10:00:00Z",
        createdAt: "2026-01-20T09:30:00Z",
    },
    {
        id: "agt_003",
        userId: mockUser.id,
        name: "Cape Strategist",
        walletAddress: "0x2D5f...b87C",
        strategyType: "balanced",
        riskLevel: "conservative",
        marketFocus: {
            regions: ["south-africa", "ghana"],
            categories: ["elections", "policy", "diplomacy"],
        },
        maxTradeSize: 300,
        dailyLossLimit: 150,
        positionLimit: 4,
        capitalAllocated: 3000,
        capitalUsed: 1900,
        status: "paused",
        pnl: -180.0,
        pnlPercent: -6.0,
        winRate: 0.48,
        totalTrades: 21,
        openPositions: 1,
        lastTradeAt: "2026-02-10T16:30:00Z",
        deployedAt: "2026-02-01T12:00:00Z",
        createdAt: "2026-02-01T11:30:00Z",
    },
];

// ─── Mock Trades ───
export const mockTrades: Trade[] = [
    {
        id: "txn_001",
        agentId: "agt_001",
        agentName: "Lagos Oracle",
        marketId: "mkt_ng_001",
        marketTitle: "Will APC win the 2027 Nigerian Presidential Election?",
        direction: "buy",
        amount: 450,
        price: 0.42,
        txHash: "0x8f4a2b3c...7d9e1f0a",
        status: "executed",
        pnl: 82.5,
        gasUsed: "0.0024",
        blockNumber: 18_542_371,
        timestamp: "2026-02-12T08:15:00Z",
    },
    {
        id: "txn_002",
        agentId: "agt_002",
        agentName: "Nairobi Hawk",
        marketId: "mkt_ke_001",
        marketTitle: "Will Kenya shilling trade above 150/USD by Q2 2026?",
        direction: "sell",
        amount: 800,
        price: 0.58,
        txHash: "0x1a2b3c4d...5e6f7g8h",
        status: "executed",
        pnl: 210.0,
        gasUsed: "0.0031",
        blockNumber: 18_542_298,
        timestamp: "2026-02-12T09:42:00Z",
    },
    {
        id: "txn_003",
        agentId: "agt_001",
        agentName: "Lagos Oracle",
        marketId: "mkt_ng_002",
        marketTitle: "Will CBN hold interest rates above 20% through Q1 2026?",
        direction: "buy",
        amount: 300,
        price: 0.73,
        txHash: "0x9b8c7d6e...5f4a3b2c",
        status: "executed",
        pnl: 45.0,
        gasUsed: "0.0019",
        blockNumber: 18_541_890,
        timestamp: "2026-02-11T22:10:00Z",
    },
    {
        id: "txn_004",
        agentId: "agt_002",
        agentName: "Nairobi Hawk",
        marketId: "mkt_et_001",
        marketTitle: "Will Ethiopia complete the GERD filling by end of 2026?",
        direction: "buy",
        amount: 600,
        price: 0.29,
        txHash: "0x3c4d5e6f...7a8b9c0d",
        status: "executed",
        pnl: -120.0,
        gasUsed: "0.0027",
        blockNumber: 18_541_654,
        timestamp: "2026-02-11T18:05:00Z",
    },
    {
        id: "txn_005",
        agentId: "agt_003",
        agentName: "Cape Strategist",
        marketId: "mkt_za_001",
        marketTitle: "Will South Africa pass the NHI Bill into full law by Dec 2026?",
        direction: "sell",
        amount: 250,
        price: 0.35,
        txHash: "0x6f7a8b9c...0d1e2f3a",
        status: "executed",
        pnl: -45.0,
        gasUsed: "0.0022",
        blockNumber: 18_540_912,
        timestamp: "2026-02-10T16:30:00Z",
    },
    {
        id: "txn_006",
        agentId: "agt_001",
        agentName: "Lagos Oracle",
        marketId: "mkt_ng_001",
        marketTitle: "Will APC win the 2027 Nigerian Presidential Election?",
        direction: "buy",
        amount: 500,
        price: 0.39,
        txHash: "0x2b3c4d5e...6f7a8b9c",
        status: "executed",
        pnl: 155.0,
        gasUsed: "0.0025",
        blockNumber: 18_540_210,
        timestamp: "2026-02-10T10:20:00Z",
    },
    {
        id: "txn_007",
        agentId: "agt_002",
        agentName: "Nairobi Hawk",
        marketId: "mkt_ke_002",
        marketTitle: "Will Kenya's Gen Z protests force a policy reversal on Finance Act 2026?",
        direction: "buy",
        amount: 950,
        price: 0.48,
        txHash: "0x0d1e2f3a...4b5c6d7e",
        status: "executed",
        pnl: 340.0,
        gasUsed: "0.0033",
        blockNumber: 18_539_780,
        timestamp: "2026-02-09T14:55:00Z",
    },
    {
        id: "txn_008",
        agentId: "agt_001",
        agentName: "Lagos Oracle",
        marketId: "mkt_gh_001",
        marketTitle: "Will Ghana's president serve full first 100 days without cabinet reshuffle?",
        direction: "sell",
        amount: 200,
        price: 0.67,
        txHash: "0x5c6d7e8f...9a0b1c2d",
        status: "pending",
        pnl: null,
        gasUsed: "0.0000",
        blockNumber: 0,
        timestamp: "2026-02-12T09:58:00Z",
    },
];

// ─── Mock Positions ───
export const mockPositions: Position[] = [
    {
        id: "pos_001",
        agentId: "agt_001",
        marketId: "mkt_ng_001",
        marketTitle: "Will APC win the 2027 Nigerian Presidential Election?",
        direction: "buy",
        entryPrice: 0.39,
        currentPrice: 0.42,
        amount: 950,
        unrealizedPnl: 28.5,
        unrealizedPnlPercent: 7.69,
        status: "open",
        openedAt: "2026-02-10T10:20:00Z",
        closedAt: null,
    },
    {
        id: "pos_002",
        agentId: "agt_001",
        marketId: "mkt_ng_002",
        marketTitle: "Will CBN hold interest rates above 20% through Q1 2026?",
        direction: "buy",
        entryPrice: 0.73,
        currentPrice: 0.76,
        amount: 300,
        unrealizedPnl: 9.0,
        unrealizedPnlPercent: 4.11,
        status: "open",
        openedAt: "2026-02-11T22:10:00Z",
        closedAt: null,
    },
    {
        id: "pos_003",
        agentId: "agt_001",
        marketId: "mkt_gh_001",
        marketTitle: "Will Ghana's president serve full first 100 days without cabinet reshuffle?",
        direction: "sell",
        entryPrice: 0.67,
        currentPrice: 0.64,
        amount: 200,
        unrealizedPnl: 6.0,
        unrealizedPnlPercent: 4.48,
        status: "open",
        openedAt: "2026-02-12T09:58:00Z",
        closedAt: null,
    },
    {
        id: "pos_004",
        agentId: "agt_002",
        marketId: "mkt_ke_001",
        marketTitle: "Will Kenya shilling trade above 150/USD by Q2 2026?",
        direction: "sell",
        entryPrice: 0.55,
        currentPrice: 0.58,
        amount: 800,
        unrealizedPnl: -24.0,
        unrealizedPnlPercent: -5.45,
        status: "open",
        openedAt: "2026-02-08T11:00:00Z",
        closedAt: null,
    },
    {
        id: "pos_005",
        agentId: "agt_002",
        marketId: "mkt_ke_002",
        marketTitle: "Will Kenya's Gen Z protests force a policy reversal on Finance Act 2026?",
        direction: "buy",
        entryPrice: 0.48,
        currentPrice: 0.51,
        amount: 950,
        unrealizedPnl: 28.5,
        unrealizedPnlPercent: 6.25,
        status: "open",
        openedAt: "2026-02-09T14:55:00Z",
        closedAt: null,
    },
    {
        id: "pos_006",
        agentId: "agt_002",
        marketId: "mkt_et_001",
        marketTitle: "Will Ethiopia complete the GERD filling by end of 2026?",
        direction: "buy",
        entryPrice: 0.29,
        currentPrice: 0.27,
        amount: 600,
        unrealizedPnl: -12.0,
        unrealizedPnlPercent: -6.90,
        status: "open",
        openedAt: "2026-02-11T18:05:00Z",
        closedAt: null,
    },
];

// ─── Mock Performance Data (30 days) ───
export const mockPerformanceData: PerformanceDataPoint[] = [
    { date: "Jan 18", pnl: 0, cumulative: 0, trades: 0 },
    { date: "Jan 20", pnl: 120, cumulative: 120, trades: 3 },
    { date: "Jan 22", pnl: -45, cumulative: 75, trades: 2 },
    { date: "Jan 24", pnl: 200, cumulative: 275, trades: 4 },
    { date: "Jan 26", pnl: 85, cumulative: 360, trades: 2 },
    { date: "Jan 28", pnl: -90, cumulative: 270, trades: 3 },
    { date: "Jan 30", pnl: 310, cumulative: 580, trades: 5 },
    { date: "Feb 01", pnl: 150, cumulative: 730, trades: 3 },
    { date: "Feb 03", pnl: -60, cumulative: 670, trades: 2 },
    { date: "Feb 05", pnl: 445, cumulative: 1115, trades: 6 },
    { date: "Feb 07", pnl: 180, cumulative: 1295, trades: 4 },
    { date: "Feb 09", pnl: 520, cumulative: 1815, trades: 7 },
    { date: "Feb 11", pnl: -30, cumulative: 1785, trades: 2 },
    { date: "Feb 12", pnl: 402.5, cumulative: 2187.5, trades: 3 },
];

// ─── Helper: get agent trades ───
export function getAgentTrades(agentId: string): Trade[] {
    return mockTrades.filter((t) => t.agentId === agentId);
}

// ─── Helper: get agent positions ───
export function getAgentPositions(agentId: string): Position[] {
    return mockPositions.filter((p) => p.agentId === agentId);
}

// ─── Helper: get agent by id ───
export function getAgentById(id: string): Agent | undefined {
    return mockAgents.find((a) => a.id === id);
}

// ─── Helper: portfolio stats ───
export function getPortfolioStats() {
    const totalCapital = mockAgents.reduce((sum, a) => sum + a.capitalAllocated, 0);
    const totalPnl = mockAgents.reduce((sum, a) => sum + a.pnl, 0);
    const activeAgents = mockAgents.filter((a) => a.status === "active").length;
    const totalTrades = mockAgents.reduce((sum, a) => sum + a.totalTrades, 0);
    const avgWinRate = mockAgents.reduce((sum, a) => sum + a.winRate, 0) / mockAgents.length;

    return {
        totalCapital,
        totalPnl,
        totalPnlPercent: (totalPnl / totalCapital) * 100,
        activeAgents,
        totalAgents: mockAgents.length,
        totalTrades,
        avgWinRate,
    };
}
